# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: armada

dist: "dist"

#gomod:
#  proxy: true

snapshot:
  name_template: "{{ .FullCommit }}"

env:
  - GOPROXY={{ if index .Env "GOPROXY"  }}{{ .Env.GOPROXY }}{{ else }}https://proxy.golang.org,direct{{ end }}
  - GOSUMDB={{ if index .Env "GOSUMDB"  }}{{ .Env.GOSUMDB }}{{ else }}sum.golang.org{{ end }}
  - DOCKER_REPO={{ if index .Env "DOCKER_REPO"  }}{{ .Env.DOCKER_REPO }}/{{ else }}gresearch/{{ end }}
  # Goreleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}
  - GOVERSION={{ if index .Env "GOVERSION"  }}{{ .Env.GOVERSION }}{{ else }}go1.21{{ end }}

builds:
  - env: [CGO_ENABLED=0]
    id: scheduler
    binary: scheduler
    main: ./cmd/scheduler/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ replace .Version "-" "_" }}_source'
  format: "zip"

archives:
  - id: armadactl
    builds:
      - armadactl
    allow_different_binary_count: true
    name_template: 'armadactl_{{ replace .Version "-" "_" }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - MAINTAINERS.md

# macOS Universal Binaries-*
universal_binaries:
  - replace: true
    id: armadactl
    name_template: 'armadactl'

sboms:
  - artifacts: archive

# TODO: Enable once we have CI setup for it. See https://goreleaser.com/customization/sign/
# signs:
#   - artifacts: checksum

dockers:
  - id: scheduler
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.DOCKER_REPO }}armada-scheduler:latest"
      - "{{ .Env.DOCKER_REPO }}armada-scheduler:{{ .Version }}"
    build_flag_templates: *BUILD_FLAG_TEMPLATES
    ids:
      - scheduler
    extra_files:
      - config/scheduler/config.yaml
    dockerfile: ./build_goreleaser/scheduler/Dockerfile

changelog:
  skip: true
  use:
    github
  sort: asc
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  disable: '{{ if index .Env "FULL_RELEASE" }}false{{ else }}true{{ end }}'
  mode: replace
  header: |
    ## Armada v{{ .Version }}

    For more info, head over to the docs page at https://armadaproject.io

    ### Armada CLI

    `armadactl` controls the Armada batch job queueing system and is used for interacting with the system.

    The CLI can be downloaded for a specific OS & Architecture from the Assets section below.

    _NOTE: The OSX binary is packaged as an universal binary and should work on both Intel and Apple Silicon based Macs._

    ### Docker images
    #### Armada Bundle
    - `docker pull {{ .Env.DOCKER_REPO }}armada:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada:latest`
    #### Armada Lookout Bundle
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-bundle:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-bundle:latest`
    #### Armada Full Bundle
    - `docker pull {{ .Env.DOCKER_REPO }}armada-full-bundle:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-full-bundle:latest`
    #### Armada Server
    - `docker pull {{ .Env.DOCKER_REPO }}armada-server:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-server:latest`
    #### Armada Executor
    - `docker pull {{ .Env.DOCKER_REPO }}armada-executor:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-executor:latest`
    #### Armada Lookout V2
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-v2:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-v2:latest`
    #### Armada Lookout Ingester V2
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-ingester-v2:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-lookout-ingester-v2:latest`
    #### Armada Event Ingester
    - `docker pull {{ .Env.DOCKER_REPO }}armada-event-ingester:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-event-ingester:latest`
    #### Armada Scheduler
    - `docker pull {{ .Env.DOCKER_REPO }}armada-scheduler:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-scheduler:latest`
    #### Armada Scheduler Ingester
    - `docker pull {{ .Env.DOCKER_REPO }}armada-scheduler-ingester:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-scheduler-ingester:latest`
    #### Armada Binoculars
    - `docker pull {{ .Env.DOCKER_REPO }}armada-binoculars:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armada-binoculars:latest`
    #### armadactl
    - `docker pull {{ .Env.DOCKER_REPO }}armadactl:{{ .Version }}`
    - `docker pull {{ .Env.DOCKER_REPO }}armadactl:latest`
  footer: |
    **Full Changelog**: https://github.com/armadaproject/armada/compare/{{ .PreviousTag }}...{{ .Tag }}